#!/usr/bin/env bash
# ==============================================================================
# Multi-Account Setup — deploy the FinOps audit role across all member accounts.
#
# Reads pillar-a/accounts.json (generated by generate-accounts-config.sh or
# written manually) and deploys the read-only IAM role into each account.
#
# HOW IT WORKS
# ------------
# From the payer account you already have cross-account access to member
# accounts. This script uses that access to deploy a CloudFormation stack
# into each member account individually (no StackSets required — works even
# if you haven't enabled trusted access for CloudFormation in Organizations).
#
# PRE-REQUISITES
# --------------
# 1. AWS CLI configured with your payer account credentials (or a role that
#    can assume roles in member accounts, e.g. OrganizationAccountAccessRole)
# 2. jq installed
# 3. pillar-a/accounts.json exists (see accounts.example.json)
#
# USAGE
# -----
#   bash pillar-a/scripts/multi-account-setup.sh [OPTIONS]
#
# OPTIONS
#   --config    Path to accounts.json (default: pillar-a/accounts.json)
#   --env       Only deploy to accounts with this env value (e.g. prod, staging)
#   --filter    Only deploy to accounts whose name contains this string
#   --mode      cfn (default) or cli
#   --dry-run   Print what would be done without making changes
#   --profile   AWS CLI profile for the payer account (default: $AWS_PROFILE)
#   -h, --help  Show help
# ==============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
TEMPLATE="${REPO_ROOT}/pillar-a/cloudformation/client-iam-role.yaml"

CONFIG_FILE="${REPO_ROOT}/pillar-a/accounts.json"
FILTER_ENV=""
FILTER_NAME=""
MODE="cfn"
DRY_RUN=false
PAYER_PROFILE="${AWS_PROFILE:-default}"
STACK_NAME="finops-audit-role"
# IAM role name in each member account that grants cross-account access FROM payer
# AWS Organizations creates this automatically: OrganizationAccountAccessRole
MEMBER_ACCESS_ROLE="OrganizationAccountAccessRole"

usage() {
  grep '^#' "$0" | grep -v '#!/' | sed 's/^# \?//' | head -50
  exit 1
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --config)  CONFIG_FILE="$2";       shift 2 ;;
    --env)     FILTER_ENV="$2";        shift 2 ;;
    --filter)  FILTER_NAME="$2";       shift 2 ;;
    --mode)    MODE="$2";              shift 2 ;;
    --dry-run) DRY_RUN=true;           shift   ;;
    --profile) PAYER_PROFILE="$2";     shift 2 ;;
    --member-access-role) MEMBER_ACCESS_ROLE="$2"; shift 2 ;;
    -h|--help) usage ;;
    *)         echo "Unknown option: $1"; usage ;;
  esac
done

command -v jq &>/dev/null || { echo "ERROR: jq is required. Install: brew install jq / apt install jq" >&2; exit 1; }
[[ -f "$CONFIG_FILE" ]] || { echo "ERROR: Config not found: ${CONFIG_FILE}"; echo "Run generate-accounts-config.sh first, or copy accounts.example.json to accounts.json"; exit 1; }
[[ "$MODE" =~ ^(cfn|cli)$ ]] || { echo "ERROR: --mode must be cfn or cli" >&2; exit 1; }

# Load config
PAYER_ID=$(jq -r '.payer_account_id' "$CONFIG_FILE")
EXTERNAL_ID=$(jq -r '.external_id' "$CONFIG_FILE")
ROLE_NAME=$(jq -r '.role_name // "FinOps-Audit-ReadOnly-Role"' "$CONFIG_FILE")
DEFAULT_REGION=$(jq -r '.default_region // "us-east-1"' "$CONFIG_FILE")

[[ "$EXTERNAL_ID" != "replace-with-openssl-rand-hex-16" ]] || {
  echo "ERROR: Replace the example external_id in accounts.json with a real secret."
  echo "Generate one: openssl rand -hex 16"
  exit 1
}

# Build account list (filter disabled accounts, then optional env/name filters)
ACCOUNTS_JSON=$(jq -c '[.accounts[] | select(.enabled != false)]' "$CONFIG_FILE")

if [[ -n "$FILTER_ENV" ]]; then
  ACCOUNTS_JSON=$(echo "$ACCOUNTS_JSON" | jq -c --arg e "$FILTER_ENV" '[.[] | select(.env == $e)]')
fi
if [[ -n "$FILTER_NAME" ]]; then
  ACCOUNTS_JSON=$(echo "$ACCOUNTS_JSON" | jq -c --arg n "$FILTER_NAME" '[.[] | select(.name | contains($n))]')
fi

TOTAL=$(echo "$ACCOUNTS_JSON" | jq 'length')
[[ "$TOTAL" -gt 0 ]] || { echo "No accounts matched the given filters."; exit 0; }

echo "=================================================="
echo " FinOps Platform — Multi-Account Setup"
echo "=================================================="
echo " Config       : ${CONFIG_FILE}"
echo " Payer account: ${PAYER_ID}"
echo " Role name    : ${ROLE_NAME}"
echo " Mode         : ${MODE}"
echo " External ID  : ****${EXTERNAL_ID: -4}"
echo " Target accts : ${TOTAL}"
[[ -n "$FILTER_ENV" ]]  && echo " Env filter   : ${FILTER_ENV}"
[[ -n "$FILTER_NAME" ]] && echo " Name filter  : ${FILTER_NAME}"
$DRY_RUN && echo " DRY RUN      : true (no changes will be made)"
echo "=================================================="
echo ""

PASSED=0
FAILED=0
SKIPPED=0
FAILED_ACCOUNTS=()

deploy_to_account() {
  local ACCT_ID="$1"
  local ACCT_NAME="$2"
  local ACCT_REGION="$3"

  local ROLE_ARN_IN_MEMBER="arn:aws:iam::${ACCT_ID}:role/${MEMBER_ACCESS_ROLE}"

  # Assume the OrganizationAccountAccessRole (or custom access role) in the member account
  local CREDS
  if ! CREDS=$(aws sts assume-role \
    --role-arn "$ROLE_ARN_IN_MEMBER" \
    --role-session-name "finops-setup-${ACCT_ID}" \
    --duration-seconds 900 \
    --profile "$PAYER_PROFILE" \
    --output json 2>&1); then
    echo "  [SKIP] ${ACCT_NAME} (${ACCT_ID}): Cannot assume ${MEMBER_ACCESS_ROLE} — ${CREDS##*: }"
    return 2
  fi

  local ACCESS_KEY SECRET_KEY SESSION_TOKEN
  ACCESS_KEY=$(echo "$CREDS"    | jq -r '.Credentials.AccessKeyId')
  SECRET_KEY=$(echo "$CREDS"    | jq -r '.Credentials.SecretAccessKey')
  SESSION_TOKEN=$(echo "$CREDS" | jq -r '.Credentials.SessionToken')

  if [[ "$MODE" == "cfn" ]]; then
    AWS_ACCESS_KEY_ID="$ACCESS_KEY" \
    AWS_SECRET_ACCESS_KEY="$SECRET_KEY" \
    AWS_SESSION_TOKEN="$SESSION_TOKEN" \
    aws cloudformation deploy \
      --template-file "$TEMPLATE" \
      --stack-name "$STACK_NAME" \
      --parameter-overrides \
          "CentralAccountId=${PAYER_ID}" \
          "ExternalId=${EXTERNAL_ID}" \
          "RoleName=${ROLE_NAME}" \
          "Environment=prod" \
          "EnableCURAccess=false" \
      --capabilities CAPABILITY_NAMED_IAM \
      --region "$ACCT_REGION" \
      --no-fail-on-empty-changeset \
      --tags ManagedBy=FinOpsPlatform Pillar=A \
      > /dev/null
  else
    # CLI mode: create/update role directly
    local TRUST_POLICY
    TRUST_POLICY=$(cat <<EOF
{
  "Version": "2012-10-17",
  "Statement": [{
    "Effect": "Allow",
    "Principal": {"AWS": "arn:aws:iam::${PAYER_ID}:root"},
    "Action": "sts:AssumeRole",
    "Condition": {"StringEquals": {"sts:ExternalId": "${EXTERNAL_ID}"}}
  }]
}
EOF
)
    if AWS_ACCESS_KEY_ID="$ACCESS_KEY" AWS_SECRET_ACCESS_KEY="$SECRET_KEY" \
       AWS_SESSION_TOKEN="$SESSION_TOKEN" \
       aws iam get-role --role-name "$ROLE_NAME" --region "$ACCT_REGION" &>/dev/null 2>&1; then
      AWS_ACCESS_KEY_ID="$ACCESS_KEY" AWS_SECRET_ACCESS_KEY="$SECRET_KEY" \
      AWS_SESSION_TOKEN="$SESSION_TOKEN" \
      aws iam update-assume-role-policy \
        --role-name "$ROLE_NAME" \
        --policy-document "$TRUST_POLICY" \
        --region "$ACCT_REGION" > /dev/null
    else
      AWS_ACCESS_KEY_ID="$ACCESS_KEY" AWS_SECRET_ACCESS_KEY="$SECRET_KEY" \
      AWS_SESSION_TOKEN="$SESSION_TOKEN" \
      aws iam create-role \
        --role-name "$ROLE_NAME" \
        --assume-role-policy-document "$TRUST_POLICY" \
        --description "FinOps read-only audit role" \
        --region "$ACCT_REGION" > /dev/null
      for POLICY_ARN in \
        "arn:aws:iam::aws:policy/ViewOnlyAccess" \
        "arn:aws:iam::aws:policy/AWSBillingReadOnlyAccess" \
        "arn:aws:iam::aws:policy/AWSComputeOptimizerReadOnlyAccess"; do
        AWS_ACCESS_KEY_ID="$ACCESS_KEY" AWS_SECRET_ACCESS_KEY="$SECRET_KEY" \
        AWS_SESSION_TOKEN="$SESSION_TOKEN" \
        aws iam attach-role-policy \
          --role-name "$ROLE_NAME" --policy-arn "$POLICY_ARN" \
          --region "$ACCT_REGION" > /dev/null
      done
    fi
  fi
}

IDX=0
while IFS= read -r ACCT; do
  IDX=$((IDX + 1))
  ACCT_ID=$(echo "$ACCT"     | jq -r '.id')
  ACCT_NAME=$(echo "$ACCT"   | jq -r '.name')
  ACCT_REGION=$(echo "$ACCT" | jq -r --arg d "$DEFAULT_REGION" '.region // $d')
  ROLE_ARN="arn:aws:iam::${ACCT_ID}:role/${ROLE_NAME}"

  printf "[%d/%d] %-20s (%s)  " "$IDX" "$TOTAL" "$ACCT_NAME" "$ACCT_ID"

  if $DRY_RUN; then
    echo "SKIP (dry-run) → would deploy ${ROLE_NAME}"
    SKIPPED=$((SKIPPED + 1))
    continue
  fi

  EXIT_CODE=0
  deploy_to_account "$ACCT_ID" "$ACCT_NAME" "$ACCT_REGION" || EXIT_CODE=$?

  if [[ "$EXIT_CODE" -eq 0 ]]; then
    echo "✓  ${ROLE_ARN}"
    PASSED=$((PASSED + 1))
  elif [[ "$EXIT_CODE" -eq 2 ]]; then
    SKIPPED=$((SKIPPED + 1))
  else
    echo "✗  FAILED"
    FAILED=$((FAILED + 1))
    FAILED_ACCOUNTS+=("${ACCT_NAME} (${ACCT_ID})")
  fi
done < <(echo "$ACCOUNTS_JSON" | jq -c '.[]')

echo ""
echo "=================================================="
echo " Results: ${PASSED} succeeded | ${SKIPPED} skipped | ${FAILED} failed"
echo "=================================================="

if [[ "${#FAILED_ACCOUNTS[@]}" -gt 0 ]]; then
  echo ""
  echo "Failed accounts:"
  printf '  - %s\n' "${FAILED_ACCOUNTS[@]}"
fi

if [[ "$PASSED" -gt 0 ]] && ! $DRY_RUN; then
  echo ""
  echo "Next step — run the multi-account audit:"
  echo ""
  echo "  python pillar-b/run_all_accounts.py \\"
  echo "    --config pillar-a/accounts.json \\"
  echo "    --output-dir pillar-d/data \\"
  echo "    --workers 8"
  echo ""
fi
